### PR TITLE
Removed references to touchtap

### PR DESCRIPTION
**Pull request by rahulrcopart**
Since we are upgrading to mui-0.19 per #18 , I have removed references to onTouchTap event in 2 places
onItemTouchTap -> onItemClick
onTouchTap -> onClick

### CODE REVIEW

**Comment by sidharthmehra** [comment]
Verified in the sandbox. Looks good.
https://codesandbox.io/s/vj81nr2v9y

**Comment by rahulrcopart** [comment]
@colshacol @sidharthmehra , thanks for approving this! I had a question about the release version for this though. Since this and #18 are breaking changes to existing version, will we need to bump major version. There would still be people using old mui

**Comment by sidharthmehra** [comment]
@rahulrcopart good call. This should be a major version upgrade.

**Comment by colshacol** [comment]
Well, boys. Looks like we just hit version 1.0.0.

🎉 🎈 🎂

**Pull request merged**
